version: 2.1

# using circleci orbs for easy understanding and clean ci setup
orbs:
  aws-ecs: circleci/aws-ecs@3.0.0
  aws-ecr: circleci/aws-ecr@8.1.2

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "calculator"
          # using commit information as tag
          tag: "latest"

      - aws-ecs/deploy-service-update:
          # making sure deployment is run only after successful image build and push
          requires:
            - aws-ecr/build-and-push-image
          family: "calculator"
          cluster: "calculator"